highligher: rogue
title: Haritha Parupudi
description: >
  First description
  <br><br>
  Second description
  <br><br>

theme: jekyll-theme-cayman
url: "https://hparupud.github.io"
lsi: false

permalink: pretty
